platform :ios, '14.1'

target 'iosApp' do
  use_frameworks!
  use_modular_headers!

  pod 'composeApp', :path => '../composeApp'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end